name: BS Trees build and test

on:
  push:
    branches:
      - main


jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fourth-task/
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Start tests
        run: go test -v ./tests/
